export type Permission = 
  | 'DASHBOARD_VIEW'
  | 'ANALYTICS_VIEW'
  | 'COMPANIES_VIEW'
  | 'COMPANIES_CREATE'
  | 'COMPANIES_EDIT'
  | 'COMPANIES_DELETE'
  | 'USERS_VIEW'
  | 'USERS_MANAGE'
  | 'ROLES_MANAGE'
  | 'APPS_VIEW_ALL'
  | 'APPS_MANAGE'
  | 'PRICING_MANAGE'
  | 'SUBSCRIPTIONS_VIEW'
  | 'LICENSES_MANAGE'
  | 'TRANSACTIONS_VIEW'
  | 'CMS_MANAGE'
  | 'PLUGINS_MANAGE'
  | 'SETTINGS_GLOBAL'
  | 'AUDIT_LOGS_VIEW';

export interface Role {
  id: string;
  name: string;
  permissions: Permission[];
}

export const DEFAULT_ROLES: Record<string, Permission[]> = {
  SUPER_ADMIN: [
    'DASHBOARD_VIEW', 'ANALYTICS_VIEW', 'COMPANIES_VIEW', 'COMPANIES_CREATE', 
    'COMPANIES_EDIT', 'COMPANIES_DELETE', 'USERS_VIEW', 'USERS_MANAGE', 
    'ROLES_MANAGE', 'APPS_VIEW_ALL', 'APPS_MANAGE', 'PRICING_MANAGE', 
    'SUBSCRIPTIONS_VIEW', 'LICENSES_MANAGE', 'TRANSACTIONS_VIEW', 
    'CMS_MANAGE', 'PLUGINS_MANAGE', 'SETTINGS_GLOBAL', 'AUDIT_LOGS_VIEW'
  ],
  ADMIN: [
    'DASHBOARD_VIEW', 'ANALYTICS_VIEW', 'USERS_VIEW', 'USERS_MANAGE',
    'APPS_VIEW_ALL', 'SUBSCRIPTIONS_VIEW'
  ],
  MANAGER: [
    'DASHBOARD_VIEW', 'ANALYTICS_VIEW', 'USERS_VIEW'
  ],
  STAFF: [
    'DASHBOARD_VIEW'
  ]
};
